### ISSUE TITLE
The version format 1.0.0-beta1 is not supported

### ISSUE THREAD

**Issue by nirekin** [ekara-platform/model#21]
Using a component tagged with an alphanumeric version doesn't work

```yaml
aws:
      repository: ekara-platform/aws-provider
      version: 1.0.0-beta1
```
At the runtime the version is converted into `v1.0.0` and the component cannot be fetched...
