### ISSUE TITLE
Wrong stuct model for Volumes

### ISSUE THREAD

**Issue by nirekin** [ekara-platform/model#23]
The current **struct** used for the Volume doesn't support the format required by Amazon Xlarge machine

Acual struct: 

```go
yamlVolume struct {
	Path string
	yamlParams `yaml:",inline"`
}
```
And we need to support :
```yaml
 volumes:
    - path: /users
      device_name: nvme1n1 # <-- This is not supported
      params:
        device_name: xvdf
        volume_type: gp2
        volume_size: 200
        delete_on_termination: true
```
