### ISSUE TITLE
Auto detect stacks into the main component

### ISSUE THREAD

**Issue by nirekin** [ekara-platform/model#40]
Stacks defined into the main component should be automatically detected. 

This means that we need to check in order into the main component to discover: 
- an `install.yml` playbook
- a `docker-compose.yml`

Doing this the stack doesn't have to be explicitly defined into the descriptor.

The stack will be deployed with the name "environmentName_environmentQualifier"

If the project want to defined the stack into the descriptor, for example to apply a template before the stack deployment, the yaml mustn't reference a component !

Example:

```yaml
stacks:
  environmentName_environmentQualifier:
    templates:
      - "docker-compose.yml"

```

**Comment by adrienlauer** [comment]
We should let the user name any stack as he likes. 

However, in the case the stack isn't mentioned in the descriptor but a compose/install.yml file is present beside the descriptor (implicit stack), we would name it automatically as `environmentName_environmentQualifier`. A shorter name would be cool but I'm not sure it's doable.

When the stack is mentioned in the descriptor, the component reference could be omitted:

```yaml
stacks:
    myStack:
        templates: [ '**/*.env' ]
``` 

Or set to `_`:

```yaml
stacks:
    myStack:
        component: _
        templates: [ '**/*.env' ]
```
